FROM node:18.13.0-slim as base

WORKDIR /frontend

COPY package.json package-lock.json /frontend/

RUN --mount=type=cache,target=/root/.npm npm ci

COPY . /frontend

RUN npm run build

EXPOSE 3000
CMD npm run start
