apiVersion: v1
kind: Namespace
metadata:
  name: freiburg-convention
  labels:
    name: freiburg-convention
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
data:
  eventConfig.json: |
    {
      "name": {
        "de": "24. Freiburger Jonglierfestival",
        "en-US": "Freiburg Juggling Convention 2023"
      },
      "preferredArticle": {
        "de": "das",
        "en-US": "the"
      },
      "start": "2023-05-26",
      "end": "2023-05-29",
      "senderMail": {
        "displayName": "Jonglieren in Freiburg e.V.",
        "address": "orga@jonglieren-in-freiburg.de"
      },
      "eventHomepage": "https://jonglieren-in-freiburg.de/?page_id=43"
    }
kind: ConfigMap
metadata:
  name: event-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: freiburg-convention
          env:
            - name: SESSION_SECRET
              value: "abc"
            - name: AWS_ACCESS_KEY_ID
              value: "AKIA6C6XE26VI3VO6CME"
            - name: AWS_SECRET_ACCESS_KEY
              value: "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"
            - name: MAIL_SENDER
              value: "CONSOLE"
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /frontend/temp
              name: database
            - mountPath: /frontend/config
              name: config-volume
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: pvc-database
        - name: config-volume
          configMap:
            name: event-config
